# Generated by Django 5.0.4 on 2024-04-29 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastral_number', models.CharField(max_length=100, verbose_name='Кадастровый номер')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('request_time', models.DateTimeField(auto_now_add=True, verbose_name='Время запроса')),
                ('response_time', models.DateTimeField(auto_now_add=True, verbose_name='Время ответа')),
                ('response', models.BooleanField(blank=True, null=True, verbose_name='Статус ответа')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
            },
        ),
    ]
